name: CEO Metrics Report (BFC)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"

jobs:
  run-ceo-metrics-bfc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install "duckdb==1.5.3" python-dotenv requests boto3

      - name: Run BFC CEO Metrics Report
        working-directory: CEO_METRICS_BFC
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
          SES_FROM_EMAIL: ${{ secrets.SES_FROM_EMAIL }}
          SES_TO_EMAIL_BFC: ${{ secrets.SES_TO_EMAIL_BFC }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: python main.py