name: data-pipeline-workflow
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "35 0 * * *"

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install pymysql pandas duckdb python-dotenv requests
      
      - name: Add GitHub Actions IP to RDS Security Group
        run: |
          MY_IP=$(curl -s https://checkip.amazonaws.com)
          aws ec2 authorize-security-group-ingress \
            --group-id sg-0b0b2e2d8c25693d2 \
            --protocol tcp \
            --port 3306 \
            --cidr $MY_IP/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2

      - name: Run data pipeline
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py

      - name: Remove GitHub Actions IP from RDS Security Group
        if: always()
        run: |
          MY_IP=$(curl -s https://checkip.amazonaws.com)
          aws ec2 revoke-security-group-ingress \
            --group-id sg-0b0b2e2d8c25693d2 \
            --protocol tcp \
            --port 3306 \
            --cidr $MY_IP/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        
      - name: Check for changes
        id: git-check
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV
          
      - name: Commit and push if changes
        if: env.changes == 'true'
        run: |
          git commit -m "Updates data index"
          git push